#!/usr/bin/env bash
# Container-side initialization script for core-pdm-manager.

set -o errexit
set -o nounset
set -o pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
GRAY='\033[0;37m'
NC='\033[0m'

print_color() {
    local color="$1"
    local message="$2"
    echo -e "${color}${message}${NC}"
}

ensure_pyproject() {
    if [[ -f pyproject.toml ]]; then
        return 0
    fi

    local python_version="${PDM_MANAGER_PYTHON_VERSION:-${PYTHON_VERSION:-3.13}}"
    python_version="${python_version%-slim}"
    if [[ -z "${python_version}" ]]; then
        python_version="3.13"
    fi

    local project_name
    project_name="$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')"

    cat > pyproject.toml <<EOF
[project]
name = "${project_name}"
version = "0.1.0"
description = "Generated by core-pdm-manager"
readme = "README.md"
requires-python = ">=${python_version}"
dependencies = []

[build-system]
requires = ["pdm-backend>=2.4.0"]
build-backend = "pdm.backend"
EOF

    print_color "$YELLOW" "[core-pdm-manager] Created missing pyproject.toml in project root."
}

print_color "$BLUE" "[core-pdm-manager] Initializing dependency tooling for project root: $(pwd)"

ensure_pyproject

print_color "$BLUE" "Configuring PDM behavior..."
pdm config python.use_venv false

if [[ "${USE_UV_BACKEND:-true}" == "true" ]]; then
    pdm config use_uv true
    print_color "$GRAY" "- use_uv=true"
else
    pdm config use_uv false
    print_color "$GRAY" "- use_uv=false"
fi

if [[ "${PDM_INSTALL_CACHE:-true}" == "true" ]]; then
    pdm config install.cache true
    print_color "$GRAY" "- install.cache=true"
else
    pdm config install.cache false
    print_color "$GRAY" "- install.cache=false"
fi

if [[ "${PDM_PARALLEL_INSTALL:-true}" == "true" ]]; then
    pdm config install.parallel true
    print_color "$GRAY" "- install.parallel=true"
else
    pdm config install.parallel false
    print_color "$GRAY" "- install.parallel=false"
fi

if [[ ! -f pdm.lock ]]; then
    print_color "$YELLOW" "Generating pdm.lock..."
    pdm lock
else
    print_color "$GREEN" "pdm.lock already exists."
fi

if [[ -f pyproject.toml ]]; then
    if poetry lock >/dev/null 2>&1; then
        print_color "$GREEN" "poetry.lock refreshed from current project metadata."
    else
        print_color "$YELLOW" "Skipping poetry.lock refresh (project may not be Poetry-compatible)."
    fi
fi

print_color "$GREEN" "[core-pdm-manager] Setup complete."
print_color "$BLUE" "Common commands:"
print_color "$GRAY" "  pdm add <package>"
print_color "$GRAY" "  pdm remove <package>"
print_color "$GRAY" "  pdm update"
print_color "$GRAY" "  pdm lock"
print_color "$GRAY" "  pdm export -f requirements --without-hashes -o requirements.txt"
