<#
.SYNOPSIS
Generate dependency artifact files for a target host repository.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$ProjectRoot,
    [Parameter()]
    [string]$ConfigFile,
    [Parameter()]
    [string]$Targets,
    [Parameter()]
    [string]$PythonVersion,
    [Parameter()]
    [switch]$SkipBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $scriptDir "common.ps1")

if (-not $PSBoundParameters.ContainsKey("ConfigFile") -or [string]::IsNullOrWhiteSpace($ConfigFile)) {
    $ConfigFile = $script:CorePdmManagerDefaultConfig
}

$resolvedProjectRoot = Get-PdmManagerProjectRoot -ProjectRoot $ProjectRoot
$resolvedConfigFile = $ConfigFile

if (-not [System.IO.Path]::IsPathRooted($resolvedConfigFile)) {
    $candidateFromCwd = Join-Path (Get-Location).Path $resolvedConfigFile
    if (Test-Path $candidateFromCwd) {
        $resolvedConfigFile = Get-PdmManagerAbsolutePath -PathValue $candidateFromCwd
    } else {
        $resolvedConfigFile = Get-PdmManagerAbsolutePath -PathValue $resolvedConfigFile -BasePath $script:CorePdmManagerRepoRoot
    }
} else {
    $resolvedConfigFile = Get-PdmManagerAbsolutePath -PathValue $resolvedConfigFile
}

Write-PdmManagerMessage -Message "[core-pdm-manager] Generating dependency files in: $resolvedProjectRoot" -Color Cyan
Test-PdmManagerDocker
Ensure-PdmManagerConfigFile -ConfigFilePath $resolvedConfigFile
Import-PdmManagerEnvFile -EnvFilePath $resolvedConfigFile

if ([string]::IsNullOrWhiteSpace($Targets)) {
    $Targets = $env:PDM_MANAGER_DEFAULT_TARGETS
    if ([string]::IsNullOrWhiteSpace($Targets)) {
        $Targets = "pyproject.toml,pdm.lock"
    }
}

if ([string]::IsNullOrWhiteSpace($PythonVersion)) {
    $PythonVersion = Get-PdmManagerPlainPythonVersion -PythonVersion (Get-PdmManagerPythonVersion -ProjectRoot $resolvedProjectRoot)
}

if ([string]::IsNullOrWhiteSpace($PythonVersion)) {
    $PythonVersion = "3.13"
}

$targetList = @(ConvertFrom-PdmManagerCsvTargets -CsvTargets $Targets)
if ($targetList.Count -eq 0) {
    throw "No targets resolved from input: $Targets"
}

function Initialize-PyprojectToml {
    <#
    .SYNOPSIS
    Creates a minimal pyproject.toml if missing.

    .PARAMETER TargetProjectRoot
    Project root path.

    .PARAMETER TargetPythonVersion
    Python version constraint value.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$TargetProjectRoot,
        [Parameter(Mandatory = $true)]
        [string]$TargetPythonVersion
    )

    $pyprojectPath = Join-Path $TargetProjectRoot "pyproject.toml"
    if (Test-Path $pyprojectPath) {
        Write-PdmManagerMessage -Message "[INFO] pyproject.toml already exists; not overwriting." -Color Yellow
        return
    }

    $projectName = Split-Path $TargetProjectRoot -Leaf
    $projectName = $projectName.ToLower().Replace(' ', '-')

    $content = @"
[project]
name = "$projectName"
version = "0.1.0"
description = "Generated by core-pdm-manager"
readme = "README.md"
requires-python = ">=$TargetPythonVersion"
dependencies = []

[build-system]
requires = ["pdm-backend>=2.4.0"]
build-backend = "pdm.backend"
"@

    Set-Content -Path $pyprojectPath -Value $content -Encoding UTF8
    Write-PdmManagerMessage -Message "[OK] Created pyproject.toml" -Color Green
}

function New-PythonVersionFile {
    <#
    .SYNOPSIS
    Writes .python-version in the target project root.

    .PARAMETER TargetProjectRoot
    Project root path.

    .PARAMETER TargetPythonVersion
    Python version value.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$TargetProjectRoot,
        [Parameter(Mandatory = $true)]
        [string]$TargetPythonVersion
    )

    Set-Content -Path (Join-Path $TargetProjectRoot ".python-version") -Value $TargetPythonVersion -Encoding UTF8
    Write-PdmManagerMessage -Message "[OK] Wrote .python-version ($TargetPythonVersion)" -Color Green
}

if (-not $SkipBuild.IsPresent) {
    Write-PdmManagerMessage -Message "[core-pdm-manager] Building manager image..." -Color Cyan
    $buildExit = Invoke-PdmManagerCompose -ProjectRoot $resolvedProjectRoot -ConfigFilePath $resolvedConfigFile -ComposeArgs @("build", "dev")
    if ($buildExit -ne 0) {
        throw "docker compose build failed with exit code $buildExit"
    }
}

foreach ($target in $targetList) {
    $normalized = $target.ToLower()

    switch ($normalized) {
        "pyproject.toml" {
            Initialize-PyprojectToml -TargetProjectRoot $resolvedProjectRoot -TargetPythonVersion $PythonVersion
        }
        "pdm.lock" {
            Initialize-PyprojectToml -TargetProjectRoot $resolvedProjectRoot -TargetPythonVersion $PythonVersion
            Write-PdmManagerMessage -Message "[core-pdm-manager] Generating pdm.lock..." -Color Cyan
            $exitCode = Invoke-PdmManagerCompose -ProjectRoot $resolvedProjectRoot -ConfigFilePath $resolvedConfigFile -ComposeArgs @("run", "--rm", "dev", "pdm", "lock")
            if ($exitCode -ne 0) { throw "Failed to generate pdm.lock" }
            Write-PdmManagerMessage -Message "[OK] Generated pdm.lock" -Color Green
        }
        "requirements.txt" {
            Initialize-PyprojectToml -TargetProjectRoot $resolvedProjectRoot -TargetPythonVersion $PythonVersion
            Write-PdmManagerMessage -Message "[core-pdm-manager] Exporting requirements.txt..." -Color Cyan
            $exitCode = Invoke-PdmManagerCompose -ProjectRoot $resolvedProjectRoot -ConfigFilePath $resolvedConfigFile -ComposeArgs @("run", "--rm", "dev", "/bin/bash", "-lc", "pdm export -f requirements --without-hashes -o requirements.txt")
            if ($exitCode -ne 0) { throw "Failed to generate requirements.txt" }
            Write-PdmManagerMessage -Message "[OK] Generated requirements.txt" -Color Green
        }
        "pipfile" {
            Initialize-PyprojectToml -TargetProjectRoot $resolvedProjectRoot -TargetPythonVersion $PythonVersion
            Write-PdmManagerMessage -Message "[core-pdm-manager] Generating Pipfile..." -Color Cyan
            $exitCode = Invoke-PdmManagerCompose -ProjectRoot $resolvedProjectRoot -ConfigFilePath $resolvedConfigFile -ComposeArgs @("run", "--rm", "dev", "python", "/opt/core-pdm-manager/internal/build_pipfile.py", "--project-root", "/workspace", "--output", "/workspace/Pipfile")
            if ($exitCode -ne 0) { throw "Failed to generate Pipfile" }
            Write-PdmManagerMessage -Message "[OK] Generated Pipfile" -Color Green
        }
        "poetry.lock" {
            Initialize-PyprojectToml -TargetProjectRoot $resolvedProjectRoot -TargetPythonVersion $PythonVersion
            Write-PdmManagerMessage -Message "[core-pdm-manager] Generating Poetry compatibility project..." -Color Cyan
            $prepExit = Invoke-PdmManagerCompose -ProjectRoot $resolvedProjectRoot -ConfigFilePath $resolvedConfigFile -ComposeArgs @("run", "--rm", "dev", "/bin/bash", "-lc", "mkdir -p /workspace/.pdm-manager/tmp/poetry && python /opt/core-pdm-manager/internal/build_poetry_pyproject.py --project-root /workspace --output /workspace/.pdm-manager/tmp/poetry/pyproject.toml")
            if ($prepExit -ne 0) { throw "Failed to prepare Poetry pyproject" }

            $lockExit = Invoke-PdmManagerCompose -ProjectRoot $resolvedProjectRoot -ConfigFilePath $resolvedConfigFile -ComposeArgs @("run", "--rm", "dev", "/bin/bash", "-lc", "poetry lock --no-interaction --directory /workspace/.pdm-manager/tmp/poetry && cp /workspace/.pdm-manager/tmp/poetry/poetry.lock /workspace/poetry.lock")
            if ($lockExit -ne 0) { throw "Failed to generate poetry.lock" }

            Write-PdmManagerMessage -Message "[OK] Generated poetry.lock" -Color Green
        }
        { $_ -in @("uv.lock", "us.lock") } {
            Initialize-PyprojectToml -TargetProjectRoot $resolvedProjectRoot -TargetPythonVersion $PythonVersion
            Write-PdmManagerMessage -Message "[core-pdm-manager] Generating uv.lock..." -Color Cyan
            $exitCode = Invoke-PdmManagerCompose -ProjectRoot $resolvedProjectRoot -ConfigFilePath $resolvedConfigFile -ComposeArgs @("run", "--rm", "dev", "uv", "lock")
            if ($exitCode -ne 0) { throw "Failed to generate uv.lock" }

            $compatPath = Join-Path $resolvedProjectRoot "us.lock"
            if (Test-Path $compatPath) {
                Remove-Item $compatPath -Force
            }

            if ($normalized -eq "us.lock") {
                Copy-Item (Join-Path $resolvedProjectRoot "uv.lock") $compatPath -Force
                Write-PdmManagerMessage -Message "[INFO] Created us.lock compatibility copy from uv.lock" -Color Yellow
            }

            Write-PdmManagerMessage -Message "[OK] Generated uv.lock" -Color Green
        }
        { $_ -in @(".python-version", "python-version") } {
            New-PythonVersionFile -TargetProjectRoot $resolvedProjectRoot -TargetPythonVersion $PythonVersion
        }
        default {
            throw "Unsupported target: $target"
        }
    }
}

Write-PdmManagerMessage -Message "[core-pdm-manager] Dependency file generation completed." -Color Green
