#!/usr/bin/env bash
# Generate dependency artifact files for the target host repository.

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=common.sh
source "${SCRIPT_DIR}/common.sh"

show_help() {
    cat <<'EOF'
Usage: generate-dep-files.sh [options]

Options:
  --project-root <path>      Target host project root.
  --config-file <path>       Config env file.
  --targets <csv>            Comma-separated targets.
  --python-version <value>   Optional value for .python-version or pyproject generation.
  --skip-build               Skip docker compose build.
  -h, --help                 Show this help.

Supported targets:
  pyproject.toml, pdm.lock, requirements.txt, Pipfile, poetry.lock, uv.lock,
  us.lock (alias for uv.lock), .python-version
EOF
}

PROJECT_ROOT_ARG=""
CONFIG_FILE_ARG="${PDM_MANAGER_DEFAULT_CONFIG_FILE}"
TARGETS_ARG=""
PYTHON_VERSION_ARG=""
SKIP_BUILD=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --project-root)
            PROJECT_ROOT_ARG="$2"
            shift 2
            ;;
        --config-file)
            CONFIG_FILE_ARG="$2"
            shift 2
            ;;
        --targets)
            TARGETS_ARG="$2"
            shift 2
            ;;
        --python-version)
            PYTHON_VERSION_ARG="$2"
            shift 2
            ;;
        --skip-build)
            SKIP_BUILD=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            pdm_manager_error "[ERROR] Unknown argument: $1"
            show_help
            exit 1
            ;;
    esac
done

PROJECT_ROOT="$(pdm_manager_detect_project_root "${PROJECT_ROOT_ARG}")"
if [[ "${CONFIG_FILE_ARG}" =~ ^[A-Za-z]:[\\/].* ]] || [[ "${CONFIG_FILE_ARG}" == /* ]]; then
    CONFIG_FILE="$(pdm_manager_absolutize_path "${CONFIG_FILE_ARG}" "$(pwd)")"
else
    if [[ -f "${CONFIG_FILE_ARG}" ]]; then
        CONFIG_FILE="$(pdm_manager_absolutize_path "${CONFIG_FILE_ARG}" "$(pwd)")"
    else
        CONFIG_FILE="$(pdm_manager_absolutize_path "${CONFIG_FILE_ARG}" "${PDM_MANAGER_REPO_ROOT}")"
    fi
fi

pdm_manager_info "[core-pdm-manager] Generating dependency files in: ${PROJECT_ROOT}"
pdm_manager_check_docker
pdm_manager_ensure_config_file "${CONFIG_FILE}"
pdm_manager_load_env_file "${CONFIG_FILE}"

if [[ -z "${TARGETS_ARG}" ]]; then
    TARGETS_ARG="${PDM_MANAGER_DEFAULT_TARGETS:-pyproject.toml,pdm.lock}"
fi

if [[ -z "${PYTHON_VERSION_ARG}" ]]; then
    PYTHON_VERSION_ARG="$(pdm_manager_python_version_plain "$(pdm_manager_detect_python_version "${PROJECT_ROOT}")")"
fi

if [[ -z "${PYTHON_VERSION_ARG}" ]]; then
    PYTHON_VERSION_ARG="3.13"
fi

declare -a TARGETS=()
pdm_manager_parse_csv_targets "${TARGETS_ARG}" TARGETS

if [[ ${#TARGETS[@]} -eq 0 ]]; then
    pdm_manager_error "[ERROR] No targets resolved from input: ${TARGETS_ARG}"
    exit 1
fi

ensure_pyproject() {
    local pyproject_path="${PROJECT_ROOT}/pyproject.toml"
    if [[ -f "${pyproject_path}" ]]; then
        pdm_manager_warn "[INFO] pyproject.toml already exists; not overwriting."
        return
    fi

    local project_name
    project_name="$(basename "${PROJECT_ROOT}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')"
    cat > "${pyproject_path}" <<EOF
[project]
name = "${project_name}"
version = "0.1.0"
description = "Generated by core-pdm-manager"
readme = "README.md"
requires-python = ">=${PYTHON_VERSION_ARG}"
dependencies = []

[build-system]
requires = ["pdm-backend>=2.4.0"]
build-backend = "pdm.backend"
EOF
    pdm_manager_success "[OK] Created pyproject.toml"
}

create_python_version_file() {
    local target_path="${PROJECT_ROOT}/.python-version"
    echo "${PYTHON_VERSION_ARG}" > "${target_path}"
    pdm_manager_success "[OK] Wrote .python-version (${PYTHON_VERSION_ARG})"
}

if [[ "${SKIP_BUILD}" == false ]]; then
    pdm_manager_info "[core-pdm-manager] Building manager image..."
    pdm_manager_run_compose "${PROJECT_ROOT}" "${CONFIG_FILE}" build dev
fi

for target in "${TARGETS[@]}"; do
    normalized_target="$(echo "${target}" | tr '[:upper:]' '[:lower:]')"
    case "${normalized_target}" in
        pyproject.toml)
            ensure_pyproject
            ;;
        pdm.lock)
            ensure_pyproject
            pdm_manager_info "[core-pdm-manager] Generating pdm.lock..."
            pdm_manager_run_compose "${PROJECT_ROOT}" "${CONFIG_FILE}" run --rm dev pdm lock
            pdm_manager_success "[OK] Generated pdm.lock"
            ;;
        requirements.txt)
            ensure_pyproject
            pdm_manager_info "[core-pdm-manager] Exporting requirements.txt..."
            pdm_manager_run_compose "${PROJECT_ROOT}" "${CONFIG_FILE}" run --rm dev /bin/bash -lc "pdm export -f requirements --without-hashes -o requirements.txt"
            pdm_manager_success "[OK] Generated requirements.txt"
            ;;
        pipfile)
            ensure_pyproject
            pdm_manager_info "[core-pdm-manager] Generating Pipfile..."
            pdm_manager_run_compose "${PROJECT_ROOT}" "${CONFIG_FILE}" run --rm dev python /opt/core-pdm-manager/internal/build_pipfile.py --project-root /workspace --output /workspace/Pipfile
            pdm_manager_success "[OK] Generated Pipfile"
            ;;
        poetry.lock)
            ensure_pyproject
            pdm_manager_info "[core-pdm-manager] Generating Poetry compatibility project..."
            pdm_manager_run_compose "${PROJECT_ROOT}" "${CONFIG_FILE}" run --rm dev /bin/bash -lc "mkdir -p /workspace/.pdm-manager/tmp/poetry && python /opt/core-pdm-manager/internal/build_poetry_pyproject.py --project-root /workspace --output /workspace/.pdm-manager/tmp/poetry/pyproject.toml"
            pdm_manager_info "[core-pdm-manager] Creating poetry.lock..."
            pdm_manager_run_compose "${PROJECT_ROOT}" "${CONFIG_FILE}" run --rm dev /bin/bash -lc "poetry lock --no-interaction --directory /workspace/.pdm-manager/tmp/poetry && cp /workspace/.pdm-manager/tmp/poetry/poetry.lock /workspace/poetry.lock"
            pdm_manager_success "[OK] Generated poetry.lock"
            ;;
        uv.lock|us.lock)
            ensure_pyproject
            pdm_manager_info "[core-pdm-manager] Generating uv.lock..."
            pdm_manager_run_compose "${PROJECT_ROOT}" "${CONFIG_FILE}" run --rm dev uv lock
            if [[ -f "${PROJECT_ROOT}/us.lock" ]]; then
                rm -f "${PROJECT_ROOT}/us.lock"
            fi
            if [[ "${normalized_target}" == "us.lock" && -f "${PROJECT_ROOT}/uv.lock" ]]; then
                cp "${PROJECT_ROOT}/uv.lock" "${PROJECT_ROOT}/us.lock"
                pdm_manager_warn "[INFO] Created us.lock compatibility copy from uv.lock"
            fi
            pdm_manager_success "[OK] Generated uv.lock"
            ;;
        .python-version|python-version)
            create_python_version_file
            ;;
        *)
            pdm_manager_error "[ERROR] Unsupported target: ${target}"
            exit 1
            ;;
    esac
done

pdm_manager_success "[core-pdm-manager] Dependency file generation completed."
