"""
Module: build_poetry_pyproject.py
Author: core-pdm-manager
Date: 2026-03-04
Version: 1.0.0

Description:
    Generate a Poetry-compatible pyproject.toml from a PEP 621 [project] definition
    so that poetry.lock can be produced in mixed toolchain environments.

Usage:
    python build_poetry_pyproject.py --project-root /workspace --output /workspace/.pdm-manager/tmp/poetry/pyproject.toml
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

from dependency_parsing import ParsedRequirement, load_project_dependency_model


def _render_poetry_value(requirement: ParsedRequirement) -> str:
    """
    Render Poetry dependency value expression.

    Args:
        requirement: Parsed requirement object.

    Returns:
        str: TOML snippet for Poetry dependency declaration.
    """

    if requirement.url:
        return f'{{url = "{requirement.url}"}}'

    if not requirement.specifier and not requirement.markers and not requirement.extras:
        return '"*"'

    fields: List[str] = []
    fields.append(f'version = "{requirement.specifier or "*"}"')

    if requirement.extras:
        extras = ", ".join(f'"{extra}"' for extra in requirement.extras)
        fields.append(f"extras = [{extras}]")

    if requirement.markers:
        fields.append(f'markers = "{requirement.markers}"')

    return "{" + ", ".join(fields) + "}"


def build_poetry_pyproject(project_root: Path, output_path: Path) -> None:
    """
    Build Poetry-compatible pyproject file.

    Args:
        project_root: Project root directory.
        output_path: Output pyproject path for Poetry lock generation.
    """

    model = load_project_dependency_model(project_root / "pyproject.toml")

    lines: List[str] = [
        "[tool.poetry]",
        f'name = "{model.name}"',
        'version = "0.1.0"',
        'description = "Generated by core-pdm-manager for poetry.lock compatibility"',
        'authors = ["core-pdm-manager <noreply@example.com>"]',
        "package-mode = false",
        "",
        "[tool.poetry.dependencies]",
        f'python = "{model.python_requires}"',
    ]

    for requirement in model.runtime_dependencies:
        lines.append(f'"{requirement.name}" = {_render_poetry_value(requirement)}')

    lines.extend(["", "[tool.poetry.group.dev.dependencies]"])
    if not model.dev_dependencies:
        lines.append("# no development dependencies detected")
    else:
        for requirement in model.dev_dependencies:
            lines.append(f'"{requirement.name}" = {_render_poetry_value(requirement)}')

    lines.extend(
        [
            "",
            "[build-system]",
            'requires = ["poetry-core>=1.8.0"]',
            'build-backend = "poetry.core.masonry.api"',
            "",
        ]
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments for script execution.

    Returns:
        argparse.Namespace: Parsed argument namespace.
    """

    parser = argparse.ArgumentParser(description="Generate Poetry pyproject.toml from pyproject.toml")
    parser.add_argument("--project-root", required=True, help="Project root path")
    parser.add_argument("--output", required=True, help="Poetry pyproject output path")
    return parser.parse_args()


def main() -> int:
    """
    Execute Poetry pyproject generation.

    Returns:
        int: Exit status code.
    """

    args = parse_args()
    project_root = Path(args.project_root).resolve()
    output_path = Path(args.output).resolve()

    build_poetry_pyproject(project_root=project_root, output_path=output_path)
    print(f"Generated Poetry pyproject: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
